### ISSUE TITLE
LOL

### ISSUE THREAD

**Issue by thesaderror** [blackhatethicalhacking/DDoS-Layer7-bheh#11]
Lol you will just hit your wifi. This code sending requests.

**Comment by blackhatethicalhacking** [comment]
Wifi? Are you doing DDOS using WIFI? You got to try on VPS, with huge bandwidth, or check a better, stronger connection option. Otherwise, sure it would :) You are sending tons of packets, in a second.

**Comment by thesaderror** [comment]
Yes : ) I just joked. xd

**Comment by blackhatethicalhacking** [comment]
XD
