### ISSUE TITLE
Not an issue but more of a question.

### ISSUE THREAD

**Issue by ZekePolarisBSH** [blackhatethicalhacking/DDoS-Layer7-bheh#3]
Why does it say to type in a link that doesn't match what the website says to put? Also why does the link change to this page's URL?

**Comment by blackhatethicalhacking** [comment]
Hello Zeke, are you using Python2 as this code is written using Python 2, also if you still have issues, need to see more info like the error messages, but first make sure to try it using Python2 not 3

**Comment by ZekePolarisBSH** [comment]
I used python as it was typed on the page but I figured out it was python2.
Also how to tell if it is working or not?

**Comment by blackhatethicalhacking** [comment]
Thats nice, you can check it by checking if its up using a site like: https://isitup.org/

**Comment by ZekePolarisBSH** [comment]
That site doesn't work for me for some reason and I tested the tool on my
own IP address.
