### ISSUE TITLE
Oops nvm found an issue...

### ISSUE THREAD

**Issue by ZekePolarisBSH** [blackhatethicalhacking/DDoS-Layer7-bheh#4]
File "'/data/data/com.termux/files/home/DDoS-Layer7-bheh/ddos-bheh-attack.py", line 24
                print "Author         :     SaintDruG"
                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Author         :    SaintDruG")?

I get this.

**Comment by ZekePolarisBSH** [comment]
Run using python2 seems to work just fine.

**Comment by blackhatethicalhacking** [comment]
you got to use python2 for this to work
